---
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy-prod:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "f4:52:63:45:e1:f9:17:89:61:f6:ba:0f:e7:65:a7:48"
      - run: scripts/deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-prod:
          filters:
            branches:
              only: master
          requires:
            - build
